import React, { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    // Navbar
    'nav.home': 'Inicio',
    'nav.pricing': 'Precios',
    'nav.features': 'Funciones',
    'nav.my_sermons': 'Mis Estudios',
    'nav.new_study': 'Nuevo Análisis',
    'nav.login': 'Login',
    'nav.try_free': 'Probar Gratis',
    'nav.logout': 'Salir',
    // Landing
    'hero.badge': 'Asistencia Homilética Digital',
    'hero.title': 'Desbloquea la Profundidad',
    'hero.title_gradient': 'de la Palabra',
    'hero.description': 'Obtén análisis históricos, literarios y teológicos en segundos. La herramienta definitiva para la preparación de sermones profundos.',
    'hero.start': 'Comenzar Ahora',
    'hero.login': 'Iniciar Sesión',
    'tag.literary': 'Tipo Literario',
    'tag.authorship': 'Autoría',
    'tag.historical': 'Contexto Histórico',
    'tag.significance': 'Significancia',
    'tag.purpose': 'Propósito',
    // Trust Bar
    'trust.advanced': 'EXÉGESIS AVANZADA',
    'trust.ai': 'MENTORÍA HOMILÉTICA',
    'trust.bible': 'BIBLIA & HISTORIA',
    // Pricing
    'pricing.badge': 'Membresías Ministeriales',
    'pricing.title': 'Potencia tu',
    'pricing.title_gradient': 'Estudio Bíblico',
    'pricing.subtitle': 'Planes diseñados por pastores para facilitar la preparación del mensaje dominical.',
    'plan.free': 'Sembrador',
    'plan.pro': 'Mentor',
    'plan.unlimited': 'Exégeta',
    'plan.free_price': 'Gratis',
    'plan.popular': 'Recomendado',
    'plan.includes_all': 'Incluye todo lo del plan anterior',
    'btn.start_free': 'Comenzar Gratis',
    'btn.choose': 'Elegir Plan',
    'btn.be_exegete': 'Suscribirme',
    // Editor Tools
    'editor.exegesis_title': 'Análisis del Pasaje',
    'editor.verse_placeholder': 'Ej: Juan 3:16',
    'editor.analyze_btn': 'Generar Análisis',
    'editor.literary': 'Tipo Literario',
    'editor.author': 'Autor',
    'editor.purpose': 'Propósito',
    'editor.historical': 'Contexto Histórico',
    'editor.significance': 'Significancia',
    'editor.credits_left': 'Estudios disponibles:',
    // Auth
    'auth.login_title': 'Iniciar Sesión',
    'auth.register_title': 'Crear Cuenta',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.confirm_password': 'Confirmar Contraseña',
    'auth.full_name': 'Nombre Completo',
    'auth.full_name_placeholder': 'Juan Pérez',
    'auth.email_placeholder': 'ejemplo@correo.com',
    'auth.login_btn': 'Entrar',
    'auth.register_btn': 'Registrarse',
    'auth.no_account': '¿No tienes una cuenta?',
    'auth.have_account': '¿Ya tienes una cuenta?',
    'auth.login_link': 'Inicia Sesión',
    'auth.register_link': 'Regístrate',
    'auth.success_login': '¡Bienvenido de nuevo!',
    'auth.error_login': 'Correo o contraseña incorrectos',
    'auth.success_title': '¡Casi listo! 🕊️',
    'auth.success_body': 'Hemos enviado un enlace de activación a',
    'auth.success_body_2': 'Por favor, revisa tu bandeja de entrada para confirmar tu cuenta y empezar a usar las herramientas de',
    'auth.go_login': 'Ir al Inicio de Sesión',
    'auth.forgot_password': 'Olvidé mi contraseña',
    'auth.continue_with': 'O continuar con',
    'auth.ministerio': 'Ministerio',
    'auth.inspired_prep': 'Preparación Inspirada',
    'auth.register_church': 'Registrar mi Iglesia',
    'auth.register_title_new': 'Crear nueva cuenta',
    'auth.register_subtitle': 'Únete a la comunidad de pastores y líderes.',
    'auth.church_name': 'Nombre de la Iglesia',
    'auth.church_placeholder': 'Iglesia Central',
    'auth.password_hint': 'Mínimo 8 caracteres para una seguridad sólida.',
    'auth.quote': '"La preparación del corazón y la palabra es el cimiento de un ministerio que perdura."',
    'auth.secure_platform': 'Plataforma Segura',
    'auth.ministerial_support': 'Respaldo Ministerial',
    'auth.confirm_password_label': 'Confirmar Contraseña',
    'pricing.investment': 'Inversión en su',
    'pricing.ministerio': 'Ministerio',
    'pricing.investment_desc': 'Elija el plan que mejor se adapte a su ritmo de estudio y preparación pastoral. Herramientas diseñadas para la excelencia teológica.',
    'pricing.essential': 'Esencial',
    'pricing.advanced': 'Avanzado',
    'pricing.teams': 'Equipos',
    'pricing.month': '/mes',
    'pricing.deep_prep': 'Preparación Profunda sin límites',
    'pricing.contact_sales': 'Contactar Ventas',
    'pricing.bento_library_title': 'La Biblioteca del Púlpito',
    'pricing.bento_library_desc': 'Acceda a miles de recursos teológicos curados para alimentar su preparación semanal.',
    'pricing.bento_sync_title': 'Sincronización Divina',
    'pricing.bento_sync_desc': 'Sus estudios disponibles en móvil, tablet y escritorio instantáneamente.',
    'pricing.bento_uptime': 'Disponibilidad',
    'pricing.bento_pastors': 'Pastores',
    'checkout.confirm_plan': 'Confirmar Plan',
    'checkout.step_desc': 'Estás a un paso de elevar tu preparación ministerial con herramientas diseñadas para la profundidad teológica.',
    'checkout.selected_sub': 'Suscripción Seleccionada',
    'checkout.change_plan': '¿Deseas cambiar de plan?',
    'checkout.explore_others': 'Explorar otros planes',
    'checkout.guarantee': 'Garantía',
    'checkout.secure_payment': 'Pago Seguro',
    'checkout.trust': 'Confianza',
    'checkout.ministerial_backing': 'Respaldo Ministerial',
    'checkout.summary_title': 'Resumen de Preparación',
    'checkout.subtotal': 'Subtotal',
    'checkout.taxes': 'Impuestos aplicables',
    'checkout.total_to_pay': 'Total a pagar',
    'checkout.promo_code': 'Código promocional',
    'checkout.apply_btn': 'Aplicar',
    'checkout.proceed_btn': 'Proceder al Pago Seguro',
    'checkout.encrypted_notice': 'Procesamiento cifrado de grado ministerial. Tus datos están bajo custodia sagrada.',
    'checkout.quote_preparation': '"La preparación diligente es la antesala de la inspiración profunda."',
    // List
    'list.title': 'Mis Estudios Exegéticos',
    'list.new_btn': 'Nuevo Análisis',
    'list.empty': 'No tienes estudios guardados aún.',
    'list.edit': 'EDITAR',
    'list.loading': 'Cargando estudios...',
    'list.subtitle': 'Gestionando la Sabiduría Divina',
    'list.search_placeholder': 'Buscar pasajes o temas...',
    'list.total_studies': 'Total Estudios',
    'list.this_month': 'Este Mes',
    'list.drafts': 'Borradores',
    'list.archived': 'Archivados',
    'list.col_reference': 'Referencia Bíblica',
    'list.col_last_edit': 'Última Edición',
    'list.col_tags': 'Etiquetas de Estudio',
    'list.col_actions': 'Acciones',
    'list.new_study_btn': 'Crear Estudio',
    'nav.library': 'Mis Estudios',
    'nav.sermon_prep': 'Crear Estudio',
    'nav.theology': 'Teología',
    'nav.archives': 'Archivos',
    'nav.settings': 'Ajustes',
    'nav.credits': 'Mis Créditos',
    'nav.unlimited': 'Ilimitados',
    'editor.bible_versions': 'Versiones Bíblicas',
    'editor.strong_lexicon': 'Léxicos Strong',
    'editor.biblical_maps': 'Geografía y Mapas',
    'editor.share_btn': 'Compartir',
    'editor.saved_ago': 'Guardado hace',
    'editor.saved_ago': 'Guardado hace',
    'editor.exegesis': 'Exégesis',
    'editor.homiletics': 'Homilética',
    'editor.application': 'Aplicación',
    'editor.prep_note': 'Nota de Preparación',
    'editor.write_here': 'Puedes seguir escribiendo notas:',
    'editor.visual_interlinear': 'Interlineal Visual',
    'editor.previous_versions': 'Versiones anteriores',
    'editor.share_draft': 'Compartir borrador',
    'editor.export_pdf': 'Exportar PDF',
    'editor.export_keynote': 'Keynote',
    'editor.resources': 'Recursos',
    // Landing New
    'hero.title_new': 'Potencia tu Mensaje, Simplifica tu Ministerio',
    'hero.description_new': 'La herramienta definitiva para preparar sermones inspiradores y organizar tu estudio bíblico en un solo lugar. Sin distracciones, solo enfoque.',
    'hero.cta_free': 'Empieza Gratis Ahora',
    'trust.title': 'Ministerios que confían en nosotros',
    'stats.pastors': 'Pastores Semanales',
    'stats.sermons': 'Sermones Creados',
    'stats.denominations': 'Denominaciones',
    'features.title': 'Preparación Inspirada',
    'features.study_title': 'Estudio Bíblico Profundo',
    'features.study_desc': 'Conecta pasajes, estudia léxicos y organiza tus referencias teológicas en una biblioteca personal intuitiva diseñada para el estudio serio.',
    'features.outline_title': 'Generación de Bosquejos',
    'features.outline_desc': 'Transforma tus reflexiones en estructuras de mensaje coherentes. Herramientas de organización que fluyen con tu proceso creativo.',
    'features.mgmt_title': 'Gestión de Mensajes',
    'features.mgmt_desc': 'Planifica series de sermones anuales y gestiona tu calendario ministerial con facilidad. Nunca pierdas el hilo de tus enseñanzas.',
    'roles.title': 'Diseñado para cada Líder',
    'roles.p1_title': 'Pastores de tiempo completo',
    'roles.p1_desc': 'Centraliza tu ministerio de enseñanza y reduce las horas de administración técnica.',
    'roles.p2_title': 'Líderes de Jóvenes',
    'roles.p2_desc': 'Crea contenido dinámico y relevante con herramientas que facilitan la comunicación visual.',
    'roles.p3_title': 'Estudiantes de Teología',
    'roles.p3_desc': 'Organiza tus notas de clase y proyectos de investigación en un entorno libre de distracciones.',
    'testimonials.title': 'Palabras desde el Púlpito',
    'faq.title': 'Preguntas Comunes',
    'faq.q1': '¿Qué tan seguros están mis datos y sermones?',
    'faq.a1': 'Utilizamos encriptación de grado bancario para asegurar que tu propiedad intelectual y notas personales estén siempre protegidas y solo accesibles para ti.',
    'faq.q2': '¿Qué traducciones de la Biblia están incluidas?',
    'faq.a2': 'Incluimos acceso a las versiones más utilizadas como RVR1960, NVI, LBLA y más para tu estudio comparativo.',
    'faq.q3': '¿Ofrecen planes para equipos pastorales de iglesias?',
    'faq.a3': 'Sí, nuestro plan Exégeta permite compartir recursos básicos, y ofrecemos planes institucionales para seminarios e iglesias grandes.',
    'cta.final_title': 'Comienza tu viaje hacia una preparación más profunda',
    'cta.final_desc': 'Únete a miles de pastores que han redescubierto el gozo de preparar el mensaje.',
    'footer.privacy': 'Privacidad',
    'footer.terms': 'Términos',
    'footer.contact': 'Contacto',
    'footer.copy': '© 2026 Preacher Studio. Preparación Inspirada.',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.pricing': 'Pricing',
    'nav.features': 'Features',
    'nav.my_sermons': 'My Studies',
    'nav.new_study': 'New Analysis',
    'nav.login': 'Login',
    'nav.try_free': 'Try Free',
    'nav.logout': 'Logout',
    // Landing
    'hero.badge': 'Digital Homiletic Assistance',
    'hero.title': 'Unlock the Depth',
    'hero.title_gradient': 'of the Word',
    'hero.description': 'Obtain historical, literary, and theological analysis in seconds. The ultimate tool for deep sermon preparation.',
    'hero.start': 'Start Now',
    'hero.login': 'Log In',
    'tag.literary': 'Literary Type',
    'tag.authorship': 'Authorship',
    'tag.historical': 'Historical Context',
    'tag.significance': 'Significance',
    'tag.purpose': 'Purpose',
    // Trust Bar
    'trust.advanced': 'ADVANCED EXEGESIS',
    'trust.ai': 'HOMILETIC MENTORSHIP',
    'trust.bible': 'BIBLE & HISTORY',
    // Pricing
    'pricing.badge': 'Ministerial Memberships',
    'pricing.title': 'Enhance your',
    'pricing.title_gradient': 'Bible Study',
    'pricing.subtitle': 'Plans designed by pastors to facilitate the preparation of the Sunday message.',
    'plan.free': 'Sower',
    'plan.pro': 'Mentor',
    'plan.unlimited': 'Exegete',
    'plan.free_price': 'Free',
    'plan.popular': 'Recommended',
    'plan.includes_all': 'Includes everything from the previous plan',
    'btn.start_free': 'Start for Free',
    'btn.choose': 'Choose Plan',
    'btn.be_exegete': 'Subscribe Now',
    // Editor Tools
    'editor.exegesis_title': 'Passage Analysis',
    'editor.verse_placeholder': 'Ex: John 3:16',
    'editor.analyze_btn': 'Generate Analysis',
    'editor.literary': 'Literary Type',
    'editor.author': 'Author',
    'editor.purpose': 'Purpose',
    'editor.historical': 'Historical Context',
    'editor.significance': 'Significance',
    'editor.credits_left': 'Available studies:',
    // Auth
    'auth.login_title': 'Log In',
    'auth.register_title': 'Create Account',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.full_name': 'Full Name',
    'auth.full_name_placeholder': 'John Doe',
    'auth.email_placeholder': 'example@email.com',
    'auth.login_btn': 'Sign In',
    'auth.register_btn': 'Sign Up',
    'auth.no_account': "Don't have an account?",
    'auth.have_account': 'Already have an account?',
    'auth.login_link': 'Log In',
    'auth.register_link': 'Register',
    'auth.success_login': 'Welcome back!',
    'auth.error_login': 'Invalid email or password',
    'auth.success_title': 'Almost ready! 🕊️',
    'auth.success_body': 'We have sent an activation link to',
    'auth.success_body_2': 'Please check your inbox to confirm your account and start using the tools from',
    'auth.go_login': 'Go to Log In',
    'auth.forgot_password': 'Forgot my password',
    'auth.continue_with': 'Or continue with',
    'auth.ministerio': 'Ministry',
    'auth.inspired_prep': 'Inspired Preparation',
    'auth.register_church': 'Register my Church',
    'auth.register_title_new': 'Create new account',
    'auth.register_subtitle': 'Join the community of pastors and leaders.',
    'auth.church_name': 'Church Name',
    'auth.church_placeholder': 'Central Church',
    'auth.password_hint': 'Minimum 8 characters for solid security.',
    'auth.quote': '"The preparation of the heart and the word is the foundation of a ministry that lasts."',
    'auth.secure_platform': 'Secure Platform',
    'auth.ministerial_support': 'Ministerial Support',
    'auth.confirm_password_label': 'Confirm Password',
    'pricing.investment': 'Investment in your',
    'pricing.ministerio': 'Ministry',
    'pricing.investment_desc': 'Choose the plan that best suits your study pace and pastoral preparation. Tools designed for theological excellence.',
    'pricing.essential': 'Essential',
    'pricing.advanced': 'Advanced',
    'pricing.teams': 'Teams',
    'pricing.month': '/month',
    'pricing.deep_prep': 'Unlimited Deep Preparation',
    'pricing.contact_sales': 'Contact Sales',
    'pricing.bento_library_title': 'The Pulpit Library',
    'pricing.bento_library_desc': 'Access thousands of curated theological resources to fuel your weekly preparation.',
    'pricing.bento_sync_title': 'Divine Synchronization',
    'pricing.bento_sync_desc': 'Your studies available on mobile, tablet, and desktop instantly.',
    'pricing.bento_uptime': 'Availability',
    'pricing.bento_pastors': 'Pastors',
    'checkout.confirm_plan': 'Confirm Plan',
    'checkout.step_desc': 'You are one step away from elevating your ministerial preparation with tools designed for theological depth.',
    'checkout.selected_sub': 'Selected Subscription',
    'checkout.change_plan': 'Do you want to change your plan?',
    'checkout.explore_others': 'Explore other plans',
    'checkout.guarantee': 'Guarantee',
    'checkout.secure_payment': 'Secure Payment',
    'checkout.trust': 'Trust',
    'checkout.ministerial_backing': 'Ministerial Support',
    'checkout.summary_title': 'Preparation Summary',
    'checkout.subtotal': 'Subtotal',
    'checkout.taxes': 'Applicable taxes',
    'checkout.total_to_pay': 'Total to pay',
    'checkout.promo_code': 'Promo code',
    'checkout.apply_btn': 'Apply',
    'checkout.proceed_btn': 'Proceed to Secure Payment',
    'checkout.encrypted_notice': 'Ministerial-grade encrypted processing. Your data is under sacred custody.',
    'checkout.quote_preparation': '"Diligent preparation is the prelude to deep inspiration."',
    // List
    'list.title': 'My Exegetical Studies',
    'list.new_btn': 'New Analysis',
    'list.empty': 'You have no saved studies yet.',
    'list.edit': 'EDIT',
    'list.loading': 'Loading studies...',
    'list.subtitle': 'Managing Divine Wisdom',
    'list.search_placeholder': 'Search passages or themes...',
    'list.total_studies': 'Total Studies',
    'list.this_month': 'This Month',
    'list.drafts': 'Drafts',
    'list.archived': 'Archived',
    'list.col_reference': 'Bible Reference',
    'list.col_last_edit': 'Last Edit',
    'list.col_tags': 'Study Tags',
    'list.col_actions': 'Actions',
    'list.new_study_btn': 'Create Study',
    'nav.library': 'My Studies',
    'nav.sermon_prep': 'Create Study',
    'nav.theology': 'Theology',
    'nav.archives': 'Archives',
    'nav.settings': 'Settings',
    'nav.credits': 'My Credits',
    'nav.unlimited': 'Unlimited',
    'editor.generate_analysis': 'Generate Analysis',
    'editor.saved_ago': 'Saved',
    'editor.exegesis': 'Exegesis',
    'editor.homiletics': 'Homiletics',
    'editor.application': 'Application',
    'editor.prep_note': 'Preparation Note',
    'editor.write_here': 'Write here to continue your inspired preparation...',
    'editor.visual_interlinear': 'Visual Interlinear',
    'editor.previous_versions': 'Previous versions',
    'editor.share_draft': 'Share draft',
    'editor.export_pdf': 'Export PDF',
    'editor.export_keynote': 'Keynote',
    'editor.resources': 'Resources',
    // Landing New
    'hero.title_new': 'Empower your Message, Simplify your Ministry',
    'hero.description_new': 'The ultimate tool for preparing inspiring sermons and organizing your Bible study in one place. No distractions, just focus.',
    'hero.cta_free': 'Start for Free Now',
    'trust.title': 'Ministries that trust us',
    'stats.pastors': 'Weekly Pastors',
    'stats.sermons': 'Sermons Created',
    'stats.denominations': 'Denominations',
    'features.title': 'Inspired Preparation',
    'features.study_title': 'Deep Bible Study',
    'features.study_desc': 'Connect passages, study lexicons, and organize your theological references in an intuitive personal library designed for serious study.',
    'features.outline_title': 'Outline Generation',
    'features.outline_desc': 'Transform your reflections into coherent message structures. Organization tools that flow with your creative process.',
    'features.mgmt_title': 'Message Management',
    'features.mgmt_desc': 'Plan annual sermon series and manage your ministerial calendar with ease. Never lose the thread of your teachings.',
    'roles.title': 'Designed for Every Leader',
    'roles.p1_title': 'Full-time Pastors',
    'roles.p1_desc': 'Centralize your teaching ministry and reduce technical administration hours.',
    'roles.p2_title': 'Youth Leaders',
    'roles.p2_desc': 'Create dynamic and relevant content with tools that facilitate visual communication.',
    'roles.p3_title': 'Theology Students',
    'roles.p3_desc': 'Organize your class notes and research projects in a distraction-free environment.',
    'testimonials.title': 'Words from the Pulpit',
    'faq.title': 'Common Questions',
    'faq.q1': 'How secure are my data and sermons?',
    'faq.a1': 'We use bank-grade encryption to ensure your intellectual property and personal notes are always protected and only accessible to you.',
    'faq.q2': 'What Bible translations are included?',
    'faq.a2': 'We include access to the most used versions like RVR1960, NIV, NASB, and more for your comparative study.',
    'faq.q3': 'Do you offer plans for church pastoral teams?',
    'faq.a3': 'Yes, our Exegete plan allows sharing basic resources, and we offer institutional plans for seminaries and large churches.',
    'cta.final_title': 'Start your journey towards deeper preparation',
    'cta.final_desc': 'Join thousands of pastors who have rediscovered the joy of message preparation.',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.contact': 'Contact',
    'footer.copy': '© 2026 Preacher Studio. Inspired Preparation.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'es' ? 'en' : 'es');
  };

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
