"""Initial SaaS schema

Revision ID: 81dde35ea43b
Revises: 
Create Date: 2026-04-02 17:32:43.979690

"""
from typing import Sequence, Union
import json
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81dde35ea43b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_id', sa.String(), nullable=True),
    sa.Column('max_queries', sa.Integer(), nullable=True),
    sa.Column('max_sermons', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('usage_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('verse_reference', sa.String(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('llm_logs')
    op.drop_table('sermon_history')
    op.drop_table('ai_metrics')
    op.add_column('profiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('plan_id', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('credits_remaining', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('subscription_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('language', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('profiles', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('profiles', 'mentorship_style',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'encouraging'::text"))
    op.create_unique_constraint(None, 'profiles', ['email'])
    op.drop_constraint(op.f('profiles_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'plans', ['plan_id'], ['id'])
    op.alter_column('sermons', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('sermons', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('sermons', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'Sermón sin título'::text"))
    op.alter_column('sermons', 'main_passage',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('sermons', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'seed'::text"))
    op.drop_index(op.f('idx_sermons_created_at'), table_name='sermons')
    op.drop_index(op.f('idx_sermons_user_id'), table_name='sermons')
    op.drop_constraint(op.f('sermons_user_id_fkey'), 'sermons', type_='foreignkey')
    op.create_foreign_key(None, 'sermons', 'profiles', ['user_id'], ['id'])
    op.drop_column('sermons', 'is_auto_saving')

    # SEED DATA: Planes y Admin
    # 1. Insertar Planes
    plans_table = sa.table('plans',
        sa.column('id', sa.String),
        sa.column('name', sa.String),
        sa.column('max_queries', sa.Integer),
        sa.column('max_sermons', sa.Integer),
        sa.column('features', sa.JSON)
    )

    op.bulk_insert(plans_table, [
        {
            'id': 'plan_sembrador',
            'name': 'Sembrador',
            'max_queries': 3,
            'max_sermons': 1,
            'features': json.dumps(['Consultas básicas', '1 Sermón'])
        },
        {
            'id': 'plan_mentor',
            'name': 'Mentor',
            'max_queries': 50,
            'max_sermons': 9999,
            'features': json.dumps(['Exégesis profunda', 'Sermones ilimitados', 'PDF'])
        },
        {
            'id': 'plan_exegeta',
            'name': 'Exégeta',
            'max_queries': 9999,
            'max_sermons': 9999,
            'features': json.dumps(['Todo lo anterior', 'Keynote', 'Acceso Beta', 'Estilo Pro'])
        }
    ])

    # 2. Configurar Admin Bypass
    # Marcamos a mdiazcabr@gmail.com como admin si existe el perfil
    op.execute("UPDATE profiles SET is_admin = true, plan_id = 'plan_exegeta' WHERE email = 'mdiazcabr@gmail.com'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sermons', sa.Column('is_auto_saving', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sermons', type_='foreignkey')
    op.create_foreign_key(op.f('sermons_user_id_fkey'), 'sermons', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_sermons_user_id'), 'sermons', ['user_id'], unique=False)
    op.create_index(op.f('idx_sermons_created_at'), 'sermons', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('sermons', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'seed'::text"))
    op.alter_column('sermons', 'main_passage',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sermons', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'Sermón sin título'::text"))
    op.alter_column('sermons', 'user_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('sermons', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_id_fkey'), 'profiles', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint(None, 'profiles', type_='unique')
    op.alter_column('profiles', 'mentorship_style',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'encouraging'::text"))
    op.alter_column('profiles', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('profiles', 'created_at')
    op.drop_column('profiles', 'language')
    op.drop_column('profiles', 'subscription_end')
    op.drop_column('profiles', 'subscription_status')
    op.drop_column('profiles', 'credits_remaining')
    op.drop_column('profiles', 'plan_id')
    op.drop_column('profiles', 'is_admin')
    op.drop_column('profiles', 'email')
    op.create_table('ai_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('sermon_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('latency_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.id'], name=op.f('ai_metrics_sermon_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_metrics_pkey'))
    )
    op.create_table('sermon_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('sermon_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('content_snapshot', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version_label', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.id'], name=op.f('sermon_history_sermon_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sermon_history_pkey'))
    )
    op.create_table('llm_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('sermon_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('prompt_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.id'], name=op.f('llm_logs_sermon_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_logs_pkey'))
    )
    op.drop_table('usage_logs')
    op.drop_table('plans')
    # ### end Alembic commands ###
